name: Generate Commit City

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Generate SVG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: lucasdias1707
        run: node generate-city.js

      - name: Commit & Push SVG
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git stash
          git pull --rebase origin main
          git stash pop
          git add dist/commit-city.svg
          git diff --cached --quiet && echo "Nothing to commit" && exit 0
          git commit -m "chore: update commit city SVG"
          git push origin main
